import type { GenreName } from "../lib/catalog";

export type GameSeed = {
  title: string;
  slug: string;
  price: number;
  /** Discount percentage and the number of days until it expires, counted from seed time. */
  discount?: { percent: number; days: number };
  genres: GenreName[];
  platforms: string[];
  /** The store's own score; leave out when the store hasn't rated the game (never invent one). */
  rating?: number;
  releaseDate: string;
  developer: string;
  publisher: string;
  stock: number;
  featured?: boolean;
  /** Real artwork overriding the generated placeholders (paths under public/). */
  art?: { cover?: string; keyArt?: string; card?: string; pageCover?: string };
};

export const games: GameSeed[] = [
  {
    title: "Elden Ring",
    slug: "elden-ring",
    price: 299.99,
    genres: ["RPG", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 140,
    featured: true,
    art: { cover: "/images/games/elden-ring/cover-hd.png", keyArt: "/images/games/elden-ring/key-art-hd.png" },
  },
  {
    title: "Sekiro: Shadows Die Twice",
    slug: "sekiro-shadows-die-twice",
    price: 249.99,
    discount: { percent: 30, days: 6 },
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.1,
    releaseDate: "2019-03-22",
    developer: "FromSoftware",
    publisher: "Activision",
    stock: 85,
    featured: true,
    art: { cover: "/images/games/sekiro-shadows-die-twice/cover-v2.png", keyArt: "/images/games/sekiro-shadows-die-twice/key-art-v2.png" },
  },
  {
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3-wild-hunt",
    price: 274.99,
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.9,
    releaseDate: "2015-05-19",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT",
    stock: 60,
    featured: true,
    art: { cover: "/images/games/the-witcher-3-wild-hunt/cover-hd.png", keyArt: "/images/games/the-witcher-3-wild-hunt/key-art-hd.png" },
  },
  {
    title: "Resident Evil 4",
    slug: "resident-evil-4",
    price: 149.99,
    discount: { percent: 40, days: 4 },
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2023-03-24",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 200,
    art: { cover: "/images/games/resident-evil-4/cover-v3.jpg", keyArt: "/images/games/resident-evil-4/key-art-v2.png", pageCover: "/images/games/resident-evil-4/page-cover.png" },
  },
  {
    title: "Europa Universalis V",
    slug: "europa-universalis-v",
    price: 224.99,
    genres: ["Strategy"],
    platforms: ["PC"],
    rating: 8.6,
    releaseDate: "2025-11-04",
    developer: "Paradox Tinto",
    publisher: "Paradox Interactive",
    stock: 95,
    art: { cover: "/images/games/europa-universalis-v/cover-v3.jpg", keyArt: "/images/games/europa-universalis-v/key-art-v3.jpg", card: "/images/games/europa-universalis-v/card-v2.jpg" },
  },
  {
    title: "Kingdom Come: Deliverance II",
    slug: "kingdom-come-deliverance-ii",
    price: 199.99,
    discount: { percent: 25, days: 8 },
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2025-02-04",
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    stock: 120,
    art: { cover: "/images/games/kingdom-come-deliverance-ii/cover-v2.jpg", keyArt: "/images/games/kingdom-come-deliverance-ii/key-art-v2.jpg", card: "/images/games/kingdom-come-deliverance-ii/card.jpg" },
  },
  {
    title: "Silent Hill f",
    slug: "silent-hill-f",
    price: 124.99,
    genres: ["Horror", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-09-25",
    developer: "NeoBards Entertainment",
    publisher: "Konami",
    stock: 70,
    art: { cover: "/images/games/silent-hill-f/cover-v3.jpg", keyArt: "/images/games/silent-hill-f/key-art-v2.jpg", card: "/images/games/silent-hill-f/card.jpg", pageCover: "/images/games/silent-hill-f/page-cover.jpg" },
  },
  {
    title: "Anno 117: Pax Romana",
    slug: "anno-117-pax-romana",
    price: 174.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2025-11-13",
    developer: "Ubisoft Mainz",
    publisher: "Ubisoft",
    stock: 0,
    art: { cover: "/images/games/anno-117-pax-romana/cover-v2.jpg", keyArt: "/images/games/anno-117-pax-romana/key-art-v2.jpg", card: "/images/games/anno-117-pax-romana/card.jpg" },
  },
  {
    title: "Death Stranding 2: On the Beach",
    slug: "death-stranding-2-on-the-beach",
    price: 99.99,
    genres: ["Adventure", "Action"],
    platforms: ["PlayStation 5"],
    rating: 9.0,
    releaseDate: "2025-06-26",
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 150,
    art: { cover: "/images/games/death-stranding-2-on-the-beach/cover-v3.jpg", keyArt: "/images/games/death-stranding-2-on-the-beach/key-art-v2.jpg", card: "/images/games/death-stranding-2-on-the-beach/card.jpg", pageCover: "/images/games/death-stranding-2-on-the-beach/page-cover.jpg" },
  },
  {
    title: "Lords of the Fallen",
    slug: "lords-of-the-fallen",
    price: 149.99,
    discount: { percent: 20, days: 5 },
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.1,
    releaseDate: "2023-10-13",
    developer: "Hexworks",
    publisher: "CI Games",
    stock: 45,
    art: { cover: "/images/games/lords-of-the-fallen/cover-v2.png", keyArt: "/images/games/lords-of-the-fallen/key-art-v2.png" },
  },
  {
    title: "Sid Meier's Civilization VII",
    slug: "civilization-vii",
    price: 199.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.9,
    releaseDate: "2025-02-11",
    developer: "Firaxis Games",
    publisher: "2K",
    stock: 30,
    art: { cover: "/images/games/civilization-vii/cover-v2.jpg", keyArt: "/images/games/civilization-vii/key-art-v2.jpg", card: "/images/games/civilization-vii/card.jpg" },
  },
  {
    title: "Clair Obscur: Expedition 33",
    slug: "clair-obscur-expedition-33",
    price: 139.99,
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2025-04-24",
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    stock: 110,
    art: { cover: "/images/games/clair-obscur-expedition-33/cover-v2.jpg", keyArt: "/images/games/clair-obscur-expedition-33/key-art-v2.jpg", card: "/images/games/clair-obscur-expedition-33/card.jpg" },
  },
  {
    title: "Doom: The Dark Ages",
    slug: "doom-the-dark-ages",
    price: 174.99,
    genres: ["Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-05-15",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    stock: 90,
    art: { cover: "/images/games/doom-the-dark-ages/cover-v2.jpg", keyArt: "/images/games/doom-the-dark-ages/key-art-v2.jpg", card: "/images/games/doom-the-dark-ages/card.jpg" },
  },
  {
    title: "Dark Souls III",
    slug: "dark-souls-iii",
    price: 164.99,
    discount: { percent: 35, days: 3 },
    genres: ["Souls-like", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2016-04-12",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 55,
    art: { cover: "/images/games/dark-souls-iii/cover-v2.png", keyArt: "/images/games/dark-souls-iii/key-art-v3.png" },
  },
  {
    title: "Resident Evil Requiem",
    slug: "resident-evil-requiem",
    price: 114.99,
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2026-02-27",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 65,
    art: { cover: "/images/games/resident-evil-requiem/page-cover.png", keyArt: "/images/games/resident-evil-requiem/key-art-v3.jpg", card: "/images/games/resident-evil-requiem/card.jpg", pageCover: "/images/games/resident-evil-requiem/page-cover.png" },
  },
  {
    title: "Ghost of Yōtei",
    slug: "ghost-of-yotei",
    price: 149.99,
    discount: { percent: 15, days: 9 },
    genres: ["Action", "Adventure"],
    platforms: ["PlayStation 5"],
    rating: 8.8,
    releaseDate: "2025-10-02",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 80,
    art: { cover: "/images/games/ghost-of-yotei/cover-v2.jpg", keyArt: "/images/games/ghost-of-yotei/key-art-v2.jpg", card: "/images/games/ghost-of-yotei/card.jpg" },
  },
  {
    title: "Monster Hunter Wilds",
    slug: "monster-hunter-wilds",
    price: 199.99,
    genres: ["Action", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.8,
    releaseDate: "2025-02-28",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 40,
    art: { cover: "/images/games/monster-hunter-wilds/cover-v2.jpg", keyArt: "/images/games/monster-hunter-wilds/key-art-v3.jpg", card: "/images/games/monster-hunter-wilds/card-v2.jpg" },
  },
  {
    title: "Hogwarts Legacy",
    slug: "hogwarts-legacy",
    price: 224.99,
    discount: { percent: 50, days: 2 },
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.0,
    releaseDate: "2023-02-10",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    stock: 175,
    art: { cover: "/images/games/hogwarts-legacy/cover-v2.png", keyArt: "/images/games/hogwarts-legacy/key-art-v2.png", card: "/images/games/hogwarts-legacy/card.jpg" },
  },
  {
    title: "Baldur's Gate 3",
    slug: "baldurs-gate-3",
    price: 249.99,
    genres: ["RPG", "Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2023-08-03",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    stock: 100,
    art: { cover: "/images/games/baldurs-gate-3/cover-v2.jpg" },
  },
  {
    title: "Black Myth: Wukong",
    slug: "black-myth-wukong",
    price: 274.99,
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.9,
    releaseDate: "2024-08-20",
    developer: "Game Science",
    publisher: "Game Science",
    stock: 75,
    art: { cover: "/images/games/black-myth-wukong/cover-v2.jpg", keyArt: "/images/games/black-myth-wukong/key-art.jpg" },
  },
  {
    title: "Darkest Dungeon II",
    slug: "darkest-dungeon-ii",
    price: 184.99,
    discount: { percent: 20, days: 7 },
    genres: ["Horror", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.2,
    releaseDate: "2023-05-08",
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    stock: 50,
    art: { cover: "/images/games/darkest-dungeon-ii/cover-v3.jpg", keyArt: "/images/games/darkest-dungeon-ii/key-art-v2.jpg", card: "/images/games/darkest-dungeon-ii/card-v2.jpg" },
  },
  {
    title: "Hollow Knight: Silksong",
    slug: "hollow-knight-silksong",
    price: 109.99,
    genres: ["Adventure", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.2,
    releaseDate: "2025-09-04",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    stock: 90,
    art: { cover: "/images/games/hollow-knight-silksong/cover-v3.jpg", keyArt: "/images/games/hollow-knight-silksong/key-art-v2.jpg", card: "/images/games/hollow-knight-silksong/card.jpg", pageCover: "/images/games/hollow-knight-silksong/page-cover.jpg" },
  },
  // --- Catalogue expansion (September 2026). Facts checked against the official Steam listings and
  // the publishers' announcements: worldwide release date, developer, publisher, platforms. Artwork is
  // the official Steam library art. No store rating yet, so `rating` is left out; no discounts.
  {
    title: "Ninja Gaiden 4",
    slug: "ninja-gaiden-4",
    price: 249.99,
    genres: ["Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-10-21",
    developer: "Team Ninja, PlatinumGames",
    publisher: "Xbox Game Studios",
    stock: 90,
    art: { cover: "/images/games/ninja-gaiden-4/cover.jpg", keyArt: "/images/games/ninja-gaiden-4/key-art.jpg" },
  },
  {
    title: "The Outer Worlds 2",
    slug: "the-outer-worlds-2",
    price: 249.99,
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-10-29",
    developer: "Obsidian Entertainment",
    publisher: "Xbox Game Studios",
    stock: 110,
    art: { cover: "/images/games/the-outer-worlds-2/cover.jpg", keyArt: "/images/games/the-outer-worlds-2/key-art.jpg" },
  },
  {
    title: "Little Nightmares III",
    slug: "little-nightmares-iii",
    price: 129.99,
    genres: ["Horror", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-10-10",
    developer: "Supermassive Games",
    publisher: "Bandai Namco Entertainment",
    stock: 120,
    art: { cover: "/images/games/little-nightmares-iii/cover.jpg", keyArt: "/images/games/little-nightmares-iii/key-art.jpg" },
  },
  {
    title: "Nioh 3",
    slug: "nioh-3",
    price: 249.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5"],
    releaseDate: "2026-02-06",
    developer: "Team Ninja",
    publisher: "Koei Tecmo",
    stock: 85,
    art: { cover: "/images/games/nioh-3/cover.jpg", keyArt: "/images/games/nioh-3/key-art.jpg" },
  },
  {
    title: "Code Vein II",
    slug: "code-vein-ii",
    price: 249.99,
    genres: ["Souls-like", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2026-01-30",
    developer: "Bandai Namco Studios",
    publisher: "Bandai Namco Entertainment",
    stock: 75,
    art: { cover: "/images/games/code-vein-ii/cover.jpg", keyArt: "/images/games/code-vein-ii/key-art.jpg" },
  },
  {
    title: "Dragon Quest VII Reimagined",
    slug: "dragon-quest-vii-reimagined",
    price: 219.99,
    genres: ["RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2026-02-05",
    developer: "Square Enix, HEXADRIVE",
    publisher: "Square Enix",
    stock: 95,
    art: { cover: "/images/games/dragon-quest-vii-reimagined/cover.jpg", keyArt: "/images/games/dragon-quest-vii-reimagined/key-art.jpg" },
  },
  {
    title: "Crimson Desert",
    slug: "crimson-desert",
    price: 249.99,
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2026-03-19",
    developer: "Pearl Abyss",
    publisher: "Pearl Abyss",
    stock: 130,
    art: { cover: "/images/games/crimson-desert/cover.jpg", keyArt: "/images/games/crimson-desert/key-art.jpg" },
  },
  {
    title: "Octopath Traveler 0",
    slug: "octopath-traveler-0",
    price: 199.99,
    genres: ["RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-12-04",
    developer: "Square Enix, DokiDoki Groove Works",
    publisher: "Square Enix",
    stock: 70,
    art: { cover: "/images/games/octopath-traveler-0/cover.jpg", keyArt: "/images/games/octopath-traveler-0/key-art.jpg" },
  },
  {
    title: "Lies of P",
    slug: "lies-of-p",
    price: 174.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2023-09-19",
    developer: "Round8 Studio",
    publisher: "NEOWIZ",
    stock: 100,
    art: { cover: "/images/games/lies-of-p/cover.jpg", keyArt: "/images/games/lies-of-p/key-art.jpg" },
  },
  {
    title: "Cyberpunk 2077",
    slug: "cyberpunk-2077",
    price: 199.99,
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2020-12-10",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT",
    stock: 160,
    art: { cover: "/images/games/cyberpunk-2077/cover.jpg", keyArt: "/images/games/cyberpunk-2077/key-art.jpg" },
  },
  {
    title: "God of War Ragnarök",
    slug: "god-of-war-ragnarok",
    price: 249.99,
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PlayStation 5"],
    releaseDate: "2022-11-09",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    stock: 120,
    art: { cover: "/images/games/god-of-war-ragnarok/cover.jpg", keyArt: "/images/games/god-of-war-ragnarok/key-art.jpg" },
  },
  {
    title: "Dead Space",
    slug: "dead-space",
    price: 174.99,
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2023-01-27",
    developer: "Motive",
    publisher: "Electronic Arts",
    stock: 80,
    art: { cover: "/images/games/dead-space/cover.jpg", keyArt: "/images/games/dead-space/key-art.jpg" },
  },
  {
    title: "Frostpunk 2",
    slug: "frostpunk-2",
    price: 159.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2024-09-20",
    developer: "11 bit studios",
    publisher: "11 bit studios",
    stock: 90,
    art: { cover: "/images/games/frostpunk-2/cover.jpg", keyArt: "/images/games/frostpunk-2/key-art.jpg" },
  },
  {
    title: "Total War: Warhammer III",
    slug: "total-war-warhammer-iii",
    price: 199.99,
    genres: ["Strategy"],
    platforms: ["PC"],
    releaseDate: "2022-02-17",
    developer: "Creative Assembly",
    publisher: "SEGA",
    stock: 110,
    art: { cover: "/images/games/total-war-warhammer-iii/cover.jpg", keyArt: "/images/games/total-war-warhammer-iii/key-art.jpg" },
  },
  {
    title: "Crusader Kings III",
    slug: "crusader-kings-iii",
    price: 169.99,
    genres: ["Strategy", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2020-09-01",
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    stock: 100,
    art: { cover: "/images/games/crusader-kings-iii/cover.jpg", keyArt: "/images/games/crusader-kings-iii/key-art.jpg" },
  },
  {
    title: "Blasphemous 2",
    slug: "blasphemous-2",
    price: 99.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-08-24",
    developer: "The Game Kitchen",
    publisher: "Team17",
    stock: 140,
    art: { cover: "/images/games/blasphemous-2/cover.jpg", keyArt: "/images/games/blasphemous-2/key-art.jpg" },
  },
];

export function coverPath(slug: string, art?: GameSeed["art"]): string {
  return art?.cover ?? `/images/games/${slug}/cover.jpg`;
}

/**
 * Real landscape images of the game, used as the page banner, the card fallback and the gallery.
 * Only official art goes here, never stand-in illustrations; add real screenshots after the key art.
 */
export function screenshotPaths(art?: GameSeed["art"]): string[] {
  return art?.keyArt ? [art.keyArt] : [];
}
