import type { GenreName } from "../lib/catalog";

export type GameSeed = {
  title: string;
  slug: string;
  price: number;
  /** Discount percentage and the number of days until it expires, counted from seed time. */
  discount?: { percent: number; days: number };
  genres: GenreName[];
  platforms: string[];
  /** The store's own score; leave out when the store hasn't rated the game (never invent one). */
  rating?: number;
  releaseDate: string;
  developer: string;
  publisher: string;
  stock: number;
  featured?: boolean;
  /** Real artwork overriding the generated placeholders (paths under public/). */
  art?: { cover?: string; keyArt?: string; card?: string; pageCover?: string };
};

export const games: GameSeed[] = [
  {
    title: "Elden Ring",
    slug: "elden-ring",
    price: 799.99,
    genres: ["RPG", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 140,
    featured: true,
    art: { cover: "/images/games/elden-ring/cover-hd.png", keyArt: "/images/games/elden-ring/key-art-hd.png" },
  },
  {
    title: "Sekiro: Shadows Die Twice",
    slug: "sekiro-shadows-die-twice",
    price: 599.99,
    discount: { percent: 40, days: 28 },
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.1,
    releaseDate: "2019-03-22",
    developer: "FromSoftware",
    publisher: "Activision",
    stock: 85,
    featured: true,
    art: { cover: "/images/games/sekiro-shadows-die-twice/cover-v2.png", keyArt: "/images/games/sekiro-shadows-die-twice/key-art-v2.png" },
  },
  {
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3-wild-hunt",
    price: 399.99,
    discount: { percent: 60, days: 35 },
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.9,
    releaseDate: "2015-05-19",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT",
    stock: 60,
    featured: true,
    art: { cover: "/images/games/the-witcher-3-wild-hunt/cover-hd.png", keyArt: "/images/games/the-witcher-3-wild-hunt/key-art-hd.png" },
  },
  {
    title: "Resident Evil 4",
    slug: "resident-evil-4",
    price: 599.99,
    discount: { percent: 40, days: 28 },
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2023-03-24",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 200,
    art: { cover: "/images/games/resident-evil-4/cover-v3.jpg", keyArt: "/images/games/resident-evil-4/key-art-v2.png", pageCover: "/images/games/resident-evil-4/page-cover.png" },
  },
  {
    title: "Europa Universalis V",
    slug: "europa-universalis-v",
    price: 799.99,
    genres: ["Strategy"],
    platforms: ["PC"],
    rating: 8.6,
    releaseDate: "2025-11-04",
    developer: "Paradox Tinto",
    publisher: "Paradox Interactive",
    stock: 95,
    art: { cover: "/images/games/europa-universalis-v/cover-v3.jpg", keyArt: "/images/games/europa-universalis-v/key-art-v3.jpg", card: "/images/games/europa-universalis-v/card-v2.jpg" },
  },
  {
    title: "Kingdom Come: Deliverance II",
    slug: "kingdom-come-deliverance-ii",
    price: 899.99,
    discount: { percent: 25, days: 24 },
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2025-02-04",
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    stock: 120,
    art: { cover: "/images/games/kingdom-come-deliverance-ii/cover-v2.jpg", keyArt: "/images/games/kingdom-come-deliverance-ii/key-art-v2.jpg", card: "/images/games/kingdom-come-deliverance-ii/card.jpg" },
  },
  {
    title: "Silent Hill f",
    slug: "silent-hill-f",
    price: 899.99,
    genres: ["Horror", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-09-25",
    developer: "NeoBards Entertainment",
    publisher: "Konami",
    stock: 70,
    art: { cover: "/images/games/silent-hill-f/cover-v3.jpg", keyArt: "/images/games/silent-hill-f/key-art-v2.jpg", card: "/images/games/silent-hill-f/card.jpg", pageCover: "/images/games/silent-hill-f/page-cover.jpg" },
  },
  {
    title: "Anno 117: Pax Romana",
    slug: "anno-117-pax-romana",
    price: 899.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2025-11-13",
    developer: "Ubisoft Mainz",
    publisher: "Ubisoft",
    stock: 0,
    art: { cover: "/images/games/anno-117-pax-romana/cover-v2.jpg", keyArt: "/images/games/anno-117-pax-romana/key-art-v2.jpg", card: "/images/games/anno-117-pax-romana/card.jpg" },
  },
  {
    title: "Death Stranding 2: On the Beach",
    slug: "death-stranding-2-on-the-beach",
    price: 1099.99,
    genres: ["Adventure", "Action"],
    platforms: ["PlayStation 5"],
    rating: 9.0,
    releaseDate: "2025-06-26",
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 150,
    art: { cover: "/images/games/death-stranding-2-on-the-beach/cover-v3.jpg", keyArt: "/images/games/death-stranding-2-on-the-beach/key-art-v2.jpg", card: "/images/games/death-stranding-2-on-the-beach/card.jpg", pageCover: "/images/games/death-stranding-2-on-the-beach/page-cover.jpg" },
  },
  {
    title: "Lords of the Fallen",
    slug: "lords-of-the-fallen",
    price: 599.99,
    discount: { percent: 60, days: 35 },
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.1,
    releaseDate: "2023-10-13",
    developer: "Hexworks",
    publisher: "CI Games",
    stock: 45,
    art: { cover: "/images/games/lords-of-the-fallen/cover-v2.png", keyArt: "/images/games/lords-of-the-fallen/key-art-v2.png" },
  },
  {
    title: "Sid Meier's Civilization VII",
    slug: "civilization-vii",
    price: 899.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.9,
    releaseDate: "2025-02-11",
    developer: "Firaxis Games",
    publisher: "2K",
    stock: 30,
    art: { cover: "/images/games/civilization-vii/cover-v2.jpg", keyArt: "/images/games/civilization-vii/key-art-v2.jpg", card: "/images/games/civilization-vii/card.jpg" },
  },
  {
    title: "Clair Obscur: Expedition 33",
    slug: "clair-obscur-expedition-33",
    price: 699.99,
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2025-04-24",
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    stock: 110,
    art: { cover: "/images/games/clair-obscur-expedition-33/cover-v2.jpg", keyArt: "/images/games/clair-obscur-expedition-33/key-art-v2.jpg", card: "/images/games/clair-obscur-expedition-33/card.jpg" },
  },
  {
    title: "Doom: The Dark Ages",
    slug: "doom-the-dark-ages",
    price: 999.99,
    genres: ["Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-05-15",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    stock: 90,
    art: { cover: "/images/games/doom-the-dark-ages/cover-v2.jpg", keyArt: "/images/games/doom-the-dark-ages/key-art-v2.jpg", card: "/images/games/doom-the-dark-ages/card.jpg" },
  },
  {
    title: "Dark Souls III",
    slug: "dark-souls-iii",
    price: 549.99,
    discount: { percent: 50, days: 42 },
    genres: ["Souls-like", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2016-04-12",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 55,
    art: { cover: "/images/games/dark-souls-iii/cover-v2.png", keyArt: "/images/games/dark-souls-iii/key-art-v3.png" },
  },
  {
    title: "Resident Evil Requiem",
    slug: "resident-evil-requiem",
    price: 1199.99,
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2026-02-27",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 65,
    art: { cover: "/images/games/resident-evil-requiem/page-cover.png", keyArt: "/images/games/resident-evil-requiem/key-art-v3.jpg", card: "/images/games/resident-evil-requiem/card.jpg", pageCover: "/images/games/resident-evil-requiem/page-cover.png" },
  },
  {
    title: "Ghost of Yōtei",
    slug: "ghost-of-yotei",
    price: 1199.99,
    discount: { percent: 15, days: 21 },
    genres: ["Action", "Adventure"],
    platforms: ["PlayStation 5"],
    rating: 8.8,
    releaseDate: "2025-10-02",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 80,
    art: { cover: "/images/games/ghost-of-yotei/cover-v2.jpg", keyArt: "/images/games/ghost-of-yotei/key-art-v2.jpg", card: "/images/games/ghost-of-yotei/card.jpg" },
  },
  {
    title: "Monster Hunter Wilds",
    slug: "monster-hunter-wilds",
    price: 999.99,
    genres: ["Action", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.8,
    releaseDate: "2025-02-28",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 40,
    art: { cover: "/images/games/monster-hunter-wilds/cover-v2.jpg", keyArt: "/images/games/monster-hunter-wilds/key-art-v3.jpg", card: "/images/games/monster-hunter-wilds/card-v2.jpg" },
  },
  {
    title: "Hogwarts Legacy",
    slug: "hogwarts-legacy",
    price: 699.99,
    discount: { percent: 50, days: 30 },
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.0,
    releaseDate: "2023-02-10",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    stock: 175,
    art: { cover: "/images/games/hogwarts-legacy/cover-v2.png", keyArt: "/images/games/hogwarts-legacy/key-art-v2.png", card: "/images/games/hogwarts-legacy/card.jpg" },
  },
  {
    title: "Baldur's Gate 3",
    slug: "baldurs-gate-3",
    price: 799.99,
    discount: { percent: 20, days: 21 },
    genres: ["RPG", "Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2023-08-03",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    stock: 100,
    art: { cover: "/images/games/baldurs-gate-3/cover-v2.jpg" },
  },
  {
    title: "Black Myth: Wukong",
    slug: "black-myth-wukong",
    price: 899.99,
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.9,
    releaseDate: "2024-08-20",
    developer: "Game Science",
    publisher: "Game Science",
    stock: 75,
    art: { cover: "/images/games/black-myth-wukong/cover-v2.jpg", keyArt: "/images/games/black-myth-wukong/key-art.jpg" },
  },
  {
    title: "Darkest Dungeon II",
    slug: "darkest-dungeon-ii",
    price: 399.99,
    discount: { percent: 30, days: 28 },
    genres: ["Horror", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.2,
    releaseDate: "2023-05-08",
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    stock: 50,
    art: { cover: "/images/games/darkest-dungeon-ii/cover-v3.jpg", keyArt: "/images/games/darkest-dungeon-ii/key-art-v2.jpg", card: "/images/games/darkest-dungeon-ii/card-v2.jpg" },
  },
  {
    title: "Hollow Knight: Silksong",
    slug: "hollow-knight-silksong",
    price: 349.99,
    genres: ["Adventure", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.2,
    releaseDate: "2025-09-04",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    stock: 90,
    art: { cover: "/images/games/hollow-knight-silksong/cover-v3.jpg", keyArt: "/images/games/hollow-knight-silksong/key-art-v2.jpg", card: "/images/games/hollow-knight-silksong/card.jpg", pageCover: "/images/games/hollow-knight-silksong/page-cover.jpg" },
  },
  // --- Catalogue expansion (September 2026). Facts checked against the official Steam listings and
  // the publishers' announcements: worldwide release date, developer, publisher, platforms. Artwork is
  // the official Steam library art. No store rating yet, so `rating` is left out; no discounts.
  {
    title: "Ninja Gaiden 4",
    slug: "ninja-gaiden-4",
    price: 899.99,
    genres: ["Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-10-21",
    developer: "Team Ninja, PlatinumGames",
    publisher: "Xbox Game Studios",
    stock: 90,
    art: { cover: "/images/games/ninja-gaiden-4/cover.jpg", keyArt: "/images/games/ninja-gaiden-4/key-art.jpg" },
  },
  {
    title: "The Outer Worlds 2",
    slug: "the-outer-worlds-2",
    price: 999.99,
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-10-29",
    developer: "Obsidian Entertainment",
    publisher: "Xbox Game Studios",
    stock: 110,
    art: { cover: "/images/games/the-outer-worlds-2/cover.jpg", keyArt: "/images/games/the-outer-worlds-2/key-art.jpg" },
  },
  {
    title: "Little Nightmares III",
    slug: "little-nightmares-iii",
    price: 549.99,
    genres: ["Horror", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-10-10",
    developer: "Supermassive Games",
    publisher: "Bandai Namco Entertainment",
    stock: 120,
    art: { cover: "/images/games/little-nightmares-iii/cover.jpg", keyArt: "/images/games/little-nightmares-iii/key-art.jpg" },
  },
  {
    title: "Nioh 3",
    slug: "nioh-3",
    price: 999.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5"],
    releaseDate: "2026-02-06",
    developer: "Team Ninja",
    publisher: "Koei Tecmo",
    stock: 85,
    art: { cover: "/images/games/nioh-3/cover.jpg", keyArt: "/images/games/nioh-3/key-art.jpg" },
  },
  {
    title: "Code Vein II",
    slug: "code-vein-ii",
    price: 899.99,
    genres: ["Souls-like", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2026-01-30",
    developer: "Bandai Namco Studios",
    publisher: "Bandai Namco Entertainment",
    stock: 75,
    art: { cover: "/images/games/code-vein-ii/cover.jpg", keyArt: "/images/games/code-vein-ii/key-art.jpg" },
  },
  {
    title: "Dragon Quest VII Reimagined",
    slug: "dragon-quest-vii-reimagined",
    price: 899.99,
    genres: ["RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2026-02-05",
    developer: "Square Enix, HEXADRIVE",
    publisher: "Square Enix",
    stock: 95,
    art: { cover: "/images/games/dragon-quest-vii-reimagined/cover.jpg", keyArt: "/images/games/dragon-quest-vii-reimagined/key-art.jpg" },
  },
  {
    title: "Crimson Desert",
    slug: "crimson-desert",
    price: 1099.99,
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2026-03-19",
    developer: "Pearl Abyss",
    publisher: "Pearl Abyss",
    stock: 130,
    art: { cover: "/images/games/crimson-desert/cover.jpg", keyArt: "/images/games/crimson-desert/key-art.jpg" },
  },
  {
    title: "Octopath Traveler 0",
    slug: "octopath-traveler-0",
    price: 799.99,
    genres: ["RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-12-04",
    developer: "Square Enix, DokiDoki Groove Works",
    publisher: "Square Enix",
    stock: 70,
    art: { cover: "/images/games/octopath-traveler-0/cover.jpg", keyArt: "/images/games/octopath-traveler-0/key-art.jpg" },
  },
  {
    title: "Lies of P",
    slug: "lies-of-p",
    price: 699.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2023-09-19",
    developer: "Round8 Studio",
    publisher: "NEOWIZ",
    stock: 100,
    art: { cover: "/images/games/lies-of-p/cover.jpg", keyArt: "/images/games/lies-of-p/key-art.jpg" },
  },
  {
    title: "Cyberpunk 2077",
    slug: "cyberpunk-2077",
    price: 599.99,
    discount: { percent: 50, days: 35 },
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2020-12-10",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT",
    stock: 160,
    art: { cover: "/images/games/cyberpunk-2077/cover.jpg", keyArt: "/images/games/cyberpunk-2077/key-art.jpg" },
  },
  {
    title: "God of War Ragnarök",
    slug: "god-of-war-ragnarok",
    price: 799.99,
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PlayStation 5"],
    releaseDate: "2022-11-09",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    stock: 120,
    art: { cover: "/images/games/god-of-war-ragnarok/cover.jpg", keyArt: "/images/games/god-of-war-ragnarok/key-art.jpg" },
  },
  {
    title: "Dead Space",
    slug: "dead-space",
    price: 699.99,
    discount: { percent: 50, days: 30 },
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2023-01-27",
    developer: "Motive",
    publisher: "Electronic Arts",
    stock: 80,
    art: { cover: "/images/games/dead-space/cover.jpg", keyArt: "/images/games/dead-space/key-art.jpg" },
  },
  {
    title: "Frostpunk 2",
    slug: "frostpunk-2",
    price: 599.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2024-09-20",
    developer: "11 bit studios",
    publisher: "11 bit studios",
    stock: 90,
    art: { cover: "/images/games/frostpunk-2/cover.jpg", keyArt: "/images/games/frostpunk-2/key-art.jpg" },
  },
  {
    title: "Total War: Warhammer III",
    slug: "total-war-warhammer-iii",
    price: 699.99,
    genres: ["Strategy"],
    platforms: ["PC"],
    releaseDate: "2022-02-17",
    developer: "Creative Assembly",
    publisher: "SEGA",
    stock: 110,
    art: { cover: "/images/games/total-war-warhammer-iii/cover.jpg", keyArt: "/images/games/total-war-warhammer-iii/key-art.jpg" },
  },
  {
    title: "Crusader Kings III",
    slug: "crusader-kings-iii",
    price: 499.99,
    genres: ["Strategy", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2020-09-01",
    developer: "Paradox Development Studio",
    publisher: "Paradox Interactive",
    stock: 100,
    art: { cover: "/images/games/crusader-kings-iii/cover.jpg", keyArt: "/images/games/crusader-kings-iii/key-art.jpg" },
  },
  {
    title: "Blasphemous 2",
    slug: "blasphemous-2",
    price: 349.99,
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-08-24",
    developer: "The Game Kitchen",
    publisher: "Team17",
    stock: 140,
    art: { cover: "/images/games/blasphemous-2/cover.jpg", keyArt: "/images/games/blasphemous-2/key-art.jpg" },
  },
  // Catalogue expansion, October 2026: official Steam artwork; no store rating until the store rates them.
  {
    title: "Subnautica 2",
    slug: "subnautica-2",
    price: 499.99,
    genres: ["Adventure"],
    platforms: ["PC", "Xbox Series X|S"],
    releaseDate: "2026-05-14",
    developer: "Unknown Worlds Entertainment",
    publisher: "Unknown Worlds Entertainment",
    stock: 120,
    art: { cover: "/images/games/subnautica-2/cover.jpg", keyArt: "/images/games/subnautica-2/key-art.jpg" },
  },
  {
    title: "Minecraft Dungeons II",
    slug: "minecraft-dungeons-ii",
    price: 549.99,
    genres: ["Family", "Action", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2026-09-29",
    developer: "Mojang Studios, Double Eleven",
    publisher: "Xbox Game Studios",
    stock: 160,
    art: { cover: "/images/games/minecraft-dungeons-ii/cover.jpg" },
  },
  {
    title: "LEGO Batman: Legacy of the Dark Knight",
    slug: "lego-batman-legacy-of-the-dark-knight",
    price: 799.99,
    genres: ["Family", "Action", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2026-05-22",
    developer: "TT Games",
    publisher: "Warner Bros. Games",
    stock: 140,
    art: { cover: "/images/games/lego-batman-legacy-of-the-dark-knight/cover.jpg", keyArt: "/images/games/lego-batman-legacy-of-the-dark-knight/key-art.jpg" },
  },
  {
    title: "Hades II",
    slug: "hades-ii",
    price: 449.99,
    genres: ["Action", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-09-25",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    stock: 110,
    art: { cover: "/images/games/hades-ii/cover.jpg", keyArt: "/images/games/hades-ii/key-art.jpg" },
  },
  {
    title: "SpongeBob SquarePants: Titans of the Tide",
    slug: "spongebob-squarepants-titans-of-the-tide",
    price: 599.99,
    genres: ["Family", "Adventure", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-11-18",
    developer: "Purple Lamp",
    publisher: "THQ Nordic",
    stock: 130,
    art: { cover: "/images/games/spongebob-squarepants-titans-of-the-tide/cover.jpg", keyArt: "/images/games/spongebob-squarepants-titans-of-the-tide/key-art.jpg" },
  },
  {
    title: "EA Sports FC 26",
    slug: "ea-sports-fc-26",
    price: 1099.99,
    discount: { percent: 50, days: 28 },
    genres: ["Sports"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-09-26",
    developer: "EA Canada, EA Romania",
    publisher: "Electronic Arts",
    stock: 200,
    art: { cover: "/images/games/ea-sports-fc-26/cover.jpg", keyArt: "/images/games/ea-sports-fc-26/key-art.jpg" },
  },
  {
    title: "NBA 2K26",
    slug: "nba-2k26",
    price: 999.99,
    discount: { percent: 40, days: 24 },
    genres: ["Sports"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-09-05",
    developer: "Visual Concepts",
    publisher: "2K",
    stock: 150,
    art: { cover: "/images/games/nba-2k26/cover.jpg", keyArt: "/images/games/nba-2k26/key-art.jpg" },
  },
  {
    title: "Sonic Racing: CrossWorlds",
    slug: "sonic-racing-crossworlds",
    price: 699.99,
    genres: ["Racing", "Family"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-09-25",
    developer: "Sonic Team",
    publisher: "SEGA",
    stock: 120,
    art: { cover: "/images/games/sonic-racing-crossworlds/cover.jpg", keyArt: "/images/games/sonic-racing-crossworlds/key-art.jpg" },
  },
  {
    title: "Assassin's Creed Shadows",
    slug: "assassins-creed-shadows",
    price: 999.99,
    discount: { percent: 30, days: 30 },
    genres: ["Action", "Adventure", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-03-20",
    developer: "Ubisoft Quebec",
    publisher: "Ubisoft",
    stock: 140,
    art: { cover: "/images/games/assassins-creed-shadows/cover.jpg", keyArt: "/images/games/assassins-creed-shadows/key-art.jpg" },
  },
  {
    title: "Split Fiction",
    slug: "split-fiction",
    price: 799.99,
    genres: ["Adventure", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-03-06",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    stock: 100,
    art: { cover: "/images/games/split-fiction/cover.jpg", keyArt: "/images/games/split-fiction/key-art.jpg" },
  },
  {
    title: "Two Point Museum",
    slug: "two-point-museum",
    price: 499.99,
    genres: ["Simulation", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2025-03-04",
    developer: "Two Point Studios",
    publisher: "SEGA",
    stock: 90,
    art: { cover: "/images/games/two-point-museum/cover.jpg", keyArt: "/images/games/two-point-museum/key-art.jpg" },
  },
  {
    title: "The Last of Us Part II Remastered",
    slug: "the-last-of-us-part-ii-remastered",
    price: 799.99,
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PlayStation 5"],
    releaseDate: "2024-01-19",
    developer: "Naughty Dog",
    publisher: "PlayStation Publishing",
    stock: 100,
    art: { cover: "/images/games/the-last-of-us-part-ii-remastered/cover.jpg", keyArt: "/images/games/the-last-of-us-part-ii-remastered/key-art.jpg" },
  },
  {
    title: "Microsoft Flight Simulator 2024",
    slug: "microsoft-flight-simulator-2024",
    price: 999.99,
    genres: ["Simulation"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2024-11-19",
    developer: "Asobo Studio",
    publisher: "Xbox Game Studios",
    stock: 80,
    art: { cover: "/images/games/microsoft-flight-simulator-2024/cover.jpg", keyArt: "/images/games/microsoft-flight-simulator-2024/key-art.jpg" },
  },
  {
    title: "LEGO Horizon Adventures",
    slug: "lego-horizon-adventures",
    price: 599.99,
    genres: ["Family", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Nintendo Switch"],
    releaseDate: "2024-11-14",
    developer: "Guerrilla Games, Studio Gobo",
    publisher: "PlayStation Publishing",
    stock: 90,
    art: { cover: "/images/games/lego-horizon-adventures/cover.jpg", keyArt: "/images/games/lego-horizon-adventures/key-art.jpg" },
  },
  {
    title: "Planet Coaster 2",
    slug: "planet-coaster-2",
    price: 699.99,
    genres: ["Simulation", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2024-11-06",
    developer: "Frontier Developments",
    publisher: "Frontier Developments",
    stock: 70,
    art: { cover: "/images/games/planet-coaster-2/cover.jpg", keyArt: "/images/games/planet-coaster-2/key-art.jpg" },
  },
  {
    title: "Sonic X Shadow Generations",
    slug: "sonic-x-shadow-generations",
    price: 599.99,
    discount: { percent: 30, days: 35 },
    genres: ["Family", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2024-10-25",
    developer: "Sonic Team",
    publisher: "SEGA",
    stock: 100,
    art: { cover: "/images/games/sonic-x-shadow-generations/cover.jpg", keyArt: "/images/games/sonic-x-shadow-generations/key-art.jpg" },
  },
  {
    title: "Balatro",
    slug: "balatro",
    price: 249.99,
    genres: ["Casual", "Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2024-02-20",
    developer: "LocalThunk",
    publisher: "Playstack",
    stock: 150,
    art: { cover: "/images/games/balatro/cover.jpg", keyArt: "/images/games/balatro/key-art.jpg" },
  },
  {
    title: "Disney Dreamlight Valley",
    slug: "disney-dreamlight-valley",
    price: 549.99,
    discount: { percent: 25, days: 30 },
    genres: ["Family", "Simulation", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-12-05",
    developer: "Gameloft",
    publisher: "Gameloft",
    stock: 140,
    art: { cover: "/images/games/disney-dreamlight-valley/cover.jpg", keyArt: "/images/games/disney-dreamlight-valley/key-art.jpg" },
  },
  {
    title: "Bluey: The Videogame",
    slug: "bluey-the-videogame",
    price: 449.99,
    discount: { percent: 20, days: 24 },
    genres: ["Family", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-11-17",
    developer: "Artax Games",
    publisher: "Outright Games",
    stock: 90,
    art: { cover: "/images/games/bluey-the-videogame/cover.jpg", keyArt: "/images/games/bluey-the-videogame/key-art.jpg" },
  },
  {
    title: "Cities: Skylines II",
    slug: "cities-skylines-ii",
    price: 699.99,
    genres: ["Simulation", "Strategy"],
    platforms: ["PC"],
    releaseDate: "2023-10-24",
    developer: "Colossal Order, Iceflake Studios",
    publisher: "Paradox Interactive",
    stock: 60,
    art: { cover: "/images/games/cities-skylines-ii/cover.jpg", keyArt: "/images/games/cities-skylines-ii/key-art.jpg" },
  },
  {
    title: "Hot Wheels Unleashed 2: Turbocharged",
    slug: "hot-wheels-unleashed-2-turbocharged",
    price: 549.99,
    discount: { percent: 40, days: 28 },
    genres: ["Racing", "Family"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-10-19",
    developer: "Milestone",
    publisher: "Milestone",
    stock: 110,
    art: { cover: "/images/games/hot-wheels-unleashed-2-turbocharged/cover.jpg", keyArt: "/images/games/hot-wheels-unleashed-2-turbocharged/key-art.jpg" },
  },
  {
    title: "PAW Patrol World",
    slug: "paw-patrol-world",
    price: 449.99,
    genres: ["Family", "Adventure"],
    platforms: ["PC"],
    releaseDate: "2023-09-29",
    developer: "3DClouds",
    publisher: "Outright Games",
    stock: 80,
    art: { cover: "/images/games/paw-patrol-world/cover.jpg", keyArt: "/images/games/paw-patrol-world/key-art.jpg" },
  },
  {
    title: "Dave the Diver",
    slug: "dave-the-diver",
    price: 349.99,
    genres: ["Adventure", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2023-06-28",
    developer: "MINTROCKET",
    publisher: "MINTROCKET",
    stock: 90,
    art: { cover: "/images/games/dave-the-diver/cover.jpg", keyArt: "/images/games/dave-the-diver/key-art.jpg" },
  },
  {
    title: "LEGO Star Wars: The Skywalker Saga",
    slug: "lego-star-wars-the-skywalker-saga",
    price: 499.99,
    discount: { percent: 60, days: 42 },
    genres: ["Family", "Action", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2022-04-05",
    developer: "TT Games",
    publisher: "Warner Bros. Games",
    stock: 120,
    art: { cover: "/images/games/lego-star-wars-the-skywalker-saga/cover.jpg", keyArt: "/images/games/lego-star-wars-the-skywalker-saga/key-art.jpg" },
  },
  {
    title: "PowerWash Simulator",
    slug: "powerwash-simulator",
    price: 299.99,
    discount: { percent: 30, days: 30 },
    genres: ["Simulation", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2022-07-14",
    developer: "FuturLab",
    publisher: "FuturLab",
    stock: 100,
    art: { cover: "/images/games/powerwash-simulator/cover.jpg", keyArt: "/images/games/powerwash-simulator/key-art.jpg" },
  },
  {
    title: "Forza Horizon 5",
    slug: "forza-horizon-5",
    price: 699.99,
    discount: { percent: 40, days: 30 },
    genres: ["Racing"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    releaseDate: "2021-11-09",
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    stock: 130,
    art: { cover: "/images/games/forza-horizon-5/cover.jpg", keyArt: "/images/games/forza-horizon-5/key-art.jpg" },
  },
  {
    title: "Overcooked! All You Can Eat",
    slug: "overcooked-all-you-can-eat",
    price: 399.99,
    discount: { percent: 50, days: 35 },
    genres: ["Family", "Casual"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2020-11-10",
    developer: "Team17, Ghost Town Games",
    publisher: "Team17",
    stock: 100,
    art: { cover: "/images/games/overcooked-all-you-can-eat/cover.jpg", keyArt: "/images/games/overcooked-all-you-can-eat/key-art.jpg" },
  },
  {
    title: "Minecraft Dungeons",
    slug: "minecraft-dungeons",
    price: 299.99,
    discount: { percent: 40, days: 28 },
    genres: ["Family", "Action", "Adventure"],
    platforms: ["PC", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2020-05-26",
    developer: "Mojang Studios, Double Eleven",
    publisher: "Xbox Game Studios",
    stock: 120,
    art: { cover: "/images/games/minecraft-dungeons/cover.jpg", keyArt: "/images/games/minecraft-dungeons/key-art.jpg" },
  },
  {
    title: "Red Dead Redemption 2",
    slug: "red-dead-redemption-2",
    price: 549.99,
    discount: { percent: 60, days: 35 },
    genres: ["Action", "Adventure"],
    platforms: ["PC"],
    releaseDate: "2018-10-26",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    stock: 110,
    art: { cover: "/images/games/red-dead-redemption-2/cover.jpg", keyArt: "/images/games/red-dead-redemption-2/key-art.jpg" },
  },
  {
    title: "The Elder Scrolls V: Skyrim Special Edition",
    slug: "the-elder-scrolls-v-skyrim-special-edition",
    price: 349.99,
    discount: { percent: 70, days: 42 },
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2016-10-28",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    stock: 120,
    art: { cover: "/images/games/the-elder-scrolls-v-skyrim-special-edition/cover.jpg", keyArt: "/images/games/the-elder-scrolls-v-skyrim-special-edition/key-art.jpg" },
  },
  {
    title: "Stardew Valley",
    slug: "stardew-valley",
    price: 199.99,
    genres: ["Simulation", "Casual", "RPG"],
    platforms: ["PC", "Nintendo Switch"],
    releaseDate: "2016-02-26",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    stock: 150,
    art: { cover: "/images/games/stardew-valley/cover.jpg", keyArt: "/images/games/stardew-valley/key-art.jpg" },
  },
  {
    title: "Euro Truck Simulator 2",
    slug: "euro-truck-simulator-2",
    price: 199.99,
    discount: { percent: 75, days: 21 },
    genres: ["Simulation"],
    platforms: ["PC"],
    releaseDate: "2012-10-18",
    developer: "SCS Software",
    publisher: "SCS Software",
    stock: 140,
    art: { cover: "/images/games/euro-truck-simulator-2/cover.jpg", keyArt: "/images/games/euro-truck-simulator-2/key-art.jpg" },
  },
  {
    title: "Tony Hawk's Pro Skater 3 + 4",
    slug: "tony-hawks-pro-skater-3-4",
    price: 699.99,
    genres: ["Sports"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    releaseDate: "2025-07-11",
    developer: "Iron Galaxy Studios",
    publisher: "Activision",
    stock: 90,
    art: { cover: "/images/games/tony-hawks-pro-skater-3-4/cover.jpg", keyArt: "/images/games/tony-hawks-pro-skater-3-4/key-art.jpg" },
  },
];

export function coverPath(slug: string, art?: GameSeed["art"]): string {
  return art?.cover ?? `/images/games/${slug}/cover.jpg`;
}

/**
 * Real landscape images of the game, used as the page banner, the card fallback and the gallery.
 * Only official art goes here, never stand-in illustrations; add real screenshots after the key art.
 */
export function screenshotPaths(art?: GameSeed["art"]): string[] {
  return art?.keyArt ? [art.keyArt] : [];
}
