import type { GenreName } from "../lib/catalog";

export type GameSeed = {
  title: string;
  slug: string;
  price: number;
  /** Discount percentage and the number of days until it expires, counted from seed time. */
  discount?: { percent: number; days: number };
  genres: GenreName[];
  platforms: string[];
  rating: number;
  releaseDate: string;
  developer: string;
  publisher: string;
  stock: number;
  featured?: boolean;
  /** Real artwork overriding the generated placeholders (paths under public/). */
  art?: { cover?: string; keyArt?: string; card?: string; pageCover?: string };
};

export const games: GameSeed[] = [
  {
    title: "Elden Ring",
    slug: "elden-ring",
    price: 299.99,
    genres: ["RPG", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2022-02-25",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 140,
    featured: true,
    art: { cover: "/images/games/elden-ring/cover-hd.png", keyArt: "/images/games/elden-ring/key-art-hd.png" },
  },
  {
    title: "Sekiro: Shadows Die Twice",
    slug: "sekiro-shadows-die-twice",
    price: 249.99,
    discount: { percent: 30, days: 6 },
    genres: ["Souls-like", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.1,
    releaseDate: "2019-03-22",
    developer: "FromSoftware",
    publisher: "Activision",
    stock: 85,
    featured: true,
    art: { cover: "/images/games/sekiro-shadows-die-twice/cover-v2.png", keyArt: "/images/games/sekiro-shadows-die-twice/key-art-v2.png" },
  },
  {
    title: "The Witcher 3: Wild Hunt",
    slug: "the-witcher-3-wild-hunt",
    price: 274.99,
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.9,
    releaseDate: "2015-05-19",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT",
    stock: 60,
    featured: true,
    art: { cover: "/images/games/the-witcher-3-wild-hunt/cover-hd.png", keyArt: "/images/games/the-witcher-3-wild-hunt/key-art-hd.png" },
  },
  {
    title: "Resident Evil 4",
    slug: "resident-evil-4",
    price: 149.99,
    discount: { percent: 40, days: 4 },
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2023-03-24",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 200,
    art: { cover: "/images/games/resident-evil-4/cover-v2.png", keyArt: "/images/games/resident-evil-4/key-art-v2.png", pageCover: "/images/games/resident-evil-4/page-cover.png" },
  },
  {
    title: "Europa Universalis V",
    slug: "europa-universalis-v",
    price: 224.99,
    genres: ["Strategy"],
    platforms: ["PC"],
    rating: 8.6,
    releaseDate: "2025-11-04",
    developer: "Paradox Tinto",
    publisher: "Paradox Interactive",
    stock: 95,
    art: { cover: "/images/games/europa-universalis-v/cover-v3.jpg", keyArt: "/images/games/europa-universalis-v/key-art-v3.jpg", card: "/images/games/europa-universalis-v/card-v2.jpg" },
  },
  {
    title: "Kingdom Come: Deliverance II",
    slug: "kingdom-come-deliverance-ii",
    price: 199.99,
    discount: { percent: 25, days: 8 },
    genres: ["RPG", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2025-02-04",
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    stock: 120,
  },
  {
    title: "Silent Hill f",
    slug: "silent-hill-f",
    price: 124.99,
    genres: ["Horror", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-09-25",
    developer: "NeoBards Entertainment",
    publisher: "Konami",
    stock: 70,
    art: { cover: "/images/games/silent-hill-f/cover-v2.jpg", keyArt: "/images/games/silent-hill-f/key-art-v2.jpg", card: "/images/games/silent-hill-f/card.jpg" },
  },
  {
    title: "Anno 117: Pax Romana",
    slug: "anno-117-pax-romana",
    price: 174.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.4,
    releaseDate: "2025-11-13",
    developer: "Ubisoft Mainz",
    publisher: "Ubisoft",
    stock: 0,
    art: { cover: "/images/games/anno-117-pax-romana/cover-v2.jpg", keyArt: "/images/games/anno-117-pax-romana/key-art-v2.jpg", card: "/images/games/anno-117-pax-romana/card.jpg" },
  },
  {
    title: "Death Stranding 2: On the Beach",
    slug: "death-stranding-2-on-the-beach",
    price: 99.99,
    genres: ["Adventure", "Action"],
    platforms: ["PlayStation 5"],
    rating: 9.0,
    releaseDate: "2025-06-26",
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 150,
  },
  {
    title: "Lords of the Fallen",
    slug: "lords-of-the-fallen",
    price: 149.99,
    discount: { percent: 20, days: 5 },
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.1,
    releaseDate: "2023-10-13",
    developer: "Hexworks",
    publisher: "CI Games",
    stock: 45,
    art: { cover: "/images/games/lords-of-the-fallen/cover-v2.png", keyArt: "/images/games/lords-of-the-fallen/key-art-v2.png" },
  },
  {
    title: "Sid Meier's Civilization VII",
    slug: "civilization-vii",
    price: 199.99,
    genres: ["Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.9,
    releaseDate: "2025-02-11",
    developer: "Firaxis Games",
    publisher: "2K",
    stock: 30,
  },
  {
    title: "Clair Obscur: Expedition 33",
    slug: "clair-obscur-expedition-33",
    price: 139.99,
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.3,
    releaseDate: "2025-04-24",
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    stock: 110,
    art: { cover: "/images/games/clair-obscur-expedition-33/cover-v2.jpg", keyArt: "/images/games/clair-obscur-expedition-33/key-art-v2.jpg", card: "/images/games/clair-obscur-expedition-33/card.jpg" },
  },
  {
    title: "Doom: The Dark Ages",
    slug: "doom-the-dark-ages",
    price: 174.99,
    genres: ["Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2025-05-15",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    stock: 90,
  },
  {
    title: "Dark Souls III",
    slug: "dark-souls-iii",
    price: 164.99,
    discount: { percent: 35, days: 3 },
    genres: ["Souls-like", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.6,
    releaseDate: "2016-04-12",
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    stock: 55,
    art: { cover: "/images/games/dark-souls-iii/cover-v2.png", keyArt: "/images/games/dark-souls-iii/key-art-v3.png" },
  },
  {
    title: "Resident Evil Requiem",
    slug: "resident-evil-requiem",
    price: 114.99,
    genres: ["Horror", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2026-02-27",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 65,
    art: { cover: "/images/games/resident-evil-requiem/page-cover.png", keyArt: "/images/games/resident-evil-requiem/key-art-v3.jpg", card: "/images/games/resident-evil-requiem/card.jpg", pageCover: "/images/games/resident-evil-requiem/page-cover.png" },
  },
  {
    title: "Ghost of Yōtei",
    slug: "ghost-of-yotei",
    price: 149.99,
    discount: { percent: 15, days: 9 },
    genres: ["Action", "Adventure"],
    platforms: ["PlayStation 5"],
    rating: 8.8,
    releaseDate: "2025-10-02",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    stock: 80,
    art: { cover: "/images/games/ghost-of-yotei/cover-v2.jpg", keyArt: "/images/games/ghost-of-yotei/key-art-v2.jpg", card: "/images/games/ghost-of-yotei/card.jpg" },
  },
  {
    title: "Monster Hunter Wilds",
    slug: "monster-hunter-wilds",
    price: 199.99,
    genres: ["Action", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.8,
    releaseDate: "2025-02-28",
    developer: "Capcom",
    publisher: "Capcom",
    stock: 40,
  },
  {
    title: "Hogwarts Legacy",
    slug: "hogwarts-legacy",
    price: 224.99,
    discount: { percent: 50, days: 2 },
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.0,
    releaseDate: "2023-02-10",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    stock: 175,
    art: { cover: "/images/games/hogwarts-legacy/cover-v2.png", keyArt: "/images/games/hogwarts-legacy/key-art-v2.png", card: "/images/games/hogwarts-legacy/card.jpg" },
  },
  {
    title: "Baldur's Gate 3",
    slug: "baldurs-gate-3",
    price: 249.99,
    genres: ["RPG", "Strategy"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 9.0,
    releaseDate: "2023-08-03",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    stock: 100,
  },
  {
    title: "Black Myth: Wukong",
    slug: "black-myth-wukong",
    price: 274.99,
    genres: ["Action", "Souls-like"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S"],
    rating: 8.9,
    releaseDate: "2024-08-20",
    developer: "Game Science",
    publisher: "Game Science",
    stock: 75,
  },
  {
    title: "Darkest Dungeon II",
    slug: "darkest-dungeon-ii",
    price: 184.99,
    discount: { percent: 20, days: 7 },
    genres: ["Horror", "RPG"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 8.2,
    releaseDate: "2023-05-08",
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    stock: 50,
  },
  {
    title: "Hollow Knight: Silksong",
    slug: "hollow-knight-silksong",
    price: 109.99,
    genres: ["Adventure", "Action"],
    platforms: ["PC", "PlayStation 5", "Xbox Series X|S", "Nintendo Switch"],
    rating: 7.2,
    releaseDate: "2025-09-04",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    stock: 90,
    art: { cover: "/images/games/hollow-knight-silksong/cover-v2.jpg", keyArt: "/images/games/hollow-knight-silksong/key-art-v2.jpg", card: "/images/games/hollow-knight-silksong/card.jpg" },
  },
];

export function coverPath(slug: string, art?: GameSeed["art"]): string {
  return art?.cover ?? `/images/games/${slug}/cover.jpg`;
}

/** The first screenshot doubles as the landscape card image and detail banner, so key art goes first. */
export function screenshotPaths(slug: string, art?: GameSeed["art"]): string[] {
  const shots = [1, 2, 3, 4].map((n) => `/images/games/${slug}/shot-${n}.jpg`);
  return art?.keyArt ? [art.keyArt, ...shots.slice(0, 3)] : shots;
}
